# languages.py

TEXTOS = {
    "es": {
        "btn_idioma": "EN",
        "btn_cv": "Descargar CV",
        "nombre_nav": "Mick Misael",
        "nav_items": {
            "sobre_mi": "Sobre mí",
            "proyectos": "Proyectos",
            "contacto": "Contacto",
        },
        "about_title": "Sobre mí",
        "about_name": "¡Hola! Soy Misael.",
        "description_1": "Soy estudiante de Ingeniería en Sistemas Computacionales en el Tecnológico Nacional de México, y actualmente trabajo como Systems Administrator, en donde gestiono infraestructura, soporte y operación de sistemas en entornos productivos.",
        "description_2": "También tengo mi propia Startup llamada StackTON, una empresa de soluciones IT. En ella soy CEO y Arquitecto Cloud con AWS.",
        "description_3": "Me caracterizo por el aprendizaje constante y la diciplina técnica. Actualmente me encuentro en proceso de obtener la certificación AWS Cloud Practitioner, fortaleciendo mis conocimientos en servicios cloud, buenas prácticas y arquitectura básica.",
        "funfact": "Amante de los gatos, arañas y el exceso de café... soy el estereotipo de mi carrera, ¿verdad? ¡Caray!",
        "skills_title": "Habilidades",
        "label_hard": "Habilidades Duras",
        "label_soft": "Habilidades Blandas",
        "label_useless": "Habilidades Inútiles",
        "habilidades_duras": [
            {"name": "AWS Cloud", "color": "orange"},
            {"name": "SysAdmin (Windows & Linux)", "color": "gray"},
            {"name": "Python & Reflex", "color": "blue"},
            {"name": "Cultura DevOps", "color": "purple"},
        ],
        "habilidades_blandas": [
            {"name": "Comunicación Asertiva", "color": "teal"},
            {"name": "Liderazgo", "color": "indigo"},
            {"name": "Trabajo en Equipo", "color": "cyan"},
            {"name": "Resolución de Problemas", "color": "crimson"},
        ],
        "habilidades_inutiles": [
            {"name": "Hablar como Gollum", "color": "grass"},
            {"name": "Silbar (Infravalorado)", "color": "yellow"},
            {"name": "Hacer Guturales", "color": "tomato"},
            {"name": "Conocer todo el lore del W2M Crew", "color": "pink"},
            {"name": "Redundar", "color": "amber"},
        ],
    },
    "en": {
        "btn_idioma": "ES",
        "btn_cv": "Download CV",
        "nombre_nav": "Mick Misael",
        "nav_items": {
            "sobre_mi": "About me",
            "proyectos": "Projects",
            "contacto": "Contact",
        },
        "about_title": "About me",
        "about_name": "Hello there! I'm Misael.",
        "description_1": "I am a Computer Systems Engineering student at Tecnológico Nacional de México and currently work as a Systems Administrator, managing infrastructure, support, and system operations in production environments.",
        "description_2": "I also lead my own IT solutions startup, StackTON, where I serve as CEO and AWS Cloud Architect.",
        "description_3": "I am driven by continuous learning and technical discipline. Currently, I am working toward my AWS Cloud Practitioner certification, deepening my expertise in cloud services, best practices, and foundational architecture.",
        "funfact": "Cat lover, spider enthusiast, and fueled by a concerning amount of coffee... I’m basically the walking stereotype of my major, aren't I? Good grief!",
        "skills_title": "Skills",
        "label_hard": "Hard Skills",
        "label_soft": "Soft Skills",
        "label_useless": "Useless Skills",
        "habilidades_duras": [
            {"name": "AWS Cloud", "color": "orange"},
            {"name": "SysAdmin (Windows & Linux)", "color": "gray"},
            {"name": "Python & Reflex", "color": "blue"},
            {"name": "DevOps Culture", "color": "purple"},
        ],
        "habilidades_blandas": [
            {"name": "Assertive Communication", "color": "teal"},
            {"name": "Leadership", "color": "indigo"},
            {"name": "Teamwork", "color": "cyan"},
            {"name": "Problem Solving", "color": "crimson"},
        ],
        "habilidades_inutiles": [
            {"name": "Gollum Impression", "color": "grass"},
            {"name": "Whistling (Underrated)", "color": "yellow"},
            {"name": "Death Growls", "color": "tomato"},
            {"name": "W2M Crew Lore Expert", "color": "pink"},
            {"name": "Redundancy", "color": "amber"},
        ],
    }
}