name: Deploy Portafolio Estático

on:
  push:
    branches: ["main"]

env: 
  AWS_REGION: us-east-1
  S3_BUCKET: mick-misael-portafolio
  CLOUDFRONT_ID: E2VAF3RLVNCWP8

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Export Reflex Static Frontend
        run: |
          # Exportamos solo el frontend como una app estática pura
          reflex export --frontend-only
          mkdir -p ./public_html
          unzip frontend.zip -d ./public_html
        env:

          API_URL: https://mickmisael.com

      - name: Deploy to S3
        run: |
          # Sincroniza archivos y borra los que ya no existen en el repo
          aws s3 sync ./public_html s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          # Le decimos a CloudFront que borre su memoria para servir lo nuevo de S3
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_ID }} --paths "/*"